### ISSUE TITLE
Failed on Kubuntu 18.10: No module named 'uinput'

### ISSUE THREAD

**Issue by YgorSilva** [rmst/yoke#14]
I've runned the yoke-enable-uinput, which went just fine but when i try to run the yoke script it gives me this error:  ModuleNotFoundError: No module named 'uinput'.
Which occurs in the yoke/service.py file on line 71.

**Comment by YgorSilva** [comment]
Sorry. Just downloaded the uinput package with pip3 and it works now.

**Comment by rmst** [comment]
Thank you for linking the fix! I've applied it in master.

**Comment by SanskritFritz** [comment]
I have the same problem, but I can't find a uinput package:
```
pip3 install --user uinput
ERROR: Could not find a version that satisfies the requirement uinput (from versions: none)
ERROR: No matching distribution found for uinput
```
How do I proceed?

**Comment by pzmarzly** [comment]
The package name in PIP is `python-uinput` (`pip3 install python-uinput`), as can be seen in [`setup.py`](https://github.com/rmst/yoke/blob/7cf90f413fae5ab3f97e67697bef77f3f8a28ec2/setup.py#L62-L65).
