### ISSUE TITLE
Add gamepad buttons

### ISSUE THREAD

**Issue by ilinas** [rmst/yoke#2]
This is a very cool concept! However to be usable in vast majority of games, one would need at least A, B, X, Y buttons. Best of luck with the project. :)

**Comment by rmst** [comment]
Definitely! But we might have to add a TCP connection to transmit button events because the current UDP connection might drop the event and that might be frustrating to a user.

**Comment by kozec** [comment]
How about transmitting entire state all the time? Then even if packet is dropped, next one will contain missing info.

If you can use binary protocol, it should be possible to fit one axis or all buttons into 2 bytes, so entire state should fit into 16B, if I'm counting it correctly.

**Comment by kozec** [comment]
Hey, I've already forgot that I'm following this :)

I've recently implemented support for "Remote RetroPad" in my application, protocol that is used by Retroarch on Android for exactly this. It sends only changes in UDP packet that basically contains 4 numbers and I have yet to see single "lost input" :)

**Comment by rmst** [comment]
#17

**Comment by rmst** [comment]
If someone makes a html/javascript version of a controller with two joysticks and buttons I'd be very happy to merge this via implementing #17 .

**Comment by kozec** [comment]
I have gamepads as svgs [here](https://github.com/kozec/sc-controller/tree/master/images/controller-images), but I'm not sure if it's possible to use js with SVG images.

**Comment by pzmarzly** [comment]
It is. SVG elements can have HTML `id`, `class` or `onclick` attributes. https://stackoverflow.com/q/2296097/5108318

**Comment by rmst** [comment]
Interesting! The main thing would be to do (re-)implement the ontouch (down, move, up) lifecycle. Basically replicating in javascript what has been done in https://github.com/rmst/yoke-android/blob/master/app/src/main/java/com/simonramstedt/yoke/JoystickView.java . Here is a tutorial on how this works in javascript https://seb.ly/2011/04/multi-touch-game-controller-in-javascripthtml5-for-ipad/ .

**Comment by pzmarzly** [comment]
I'll try implementing it

**Comment by pzmarzly** [comment]
I hate Javascript and Samsung OS is garbage, but there you go https://github.com/pzmarzly/html-touch-joystick.

With right config (see `const`s in `base.js`) it will output current status to console, which you [can grab](https://developer.android.com/guide/webapps/debugging#java).

It was made with user in mind - by editing CSS, user can easily change layout and behavior (`animation-name: locking;` for locking behavior - on [video](https://youtu.be/sXc8lXoid1I?t=9) I set it for left joystick). I also added 4 buttons.

I added 32 buttons in code, but user can disable any unwanted button in [UI settings](https://github.com/pzmarzly/html-touch-joystick/blob/607a4df8ff6fd79c946e8e785c3f7e8d3cb9b985/user-default.css#L8-L16)

**Comment by rmst** [comment]
Awesome, thanks! I'm going to try to incorporate it in the app statically first and then dynamically as proposed in #17 .

**Comment by pzmarzly** [comment]
Done in #19 . Thanks

**Comment by rgarrigue** [comment]
Hi ! Seems yoke is exactly what I was looking for, except for this "almost available" feature. Seems only windows is yet to be finished, can I use the RC for linux ? F-Droid release is 7 months old, I guess that's not it.

**Comment by pzmarzly** [comment]
RC is a redesign, you are welcome to test it (works fine for us, but since it uses Android Webview results may vary depending on the device). Here's the [latest APK](https://github.com/rmst/yoke/blob/master/devel/app-debug.apk). You can clone the repo and run `pip3 install .`. Button configuration can be tweaked in `yoke/yoke/assets/joypad/*.css`. I'm not sure if Windows build works

**Comment by rgarrigue** [comment]
Thanks @pzmarzly. Tried it. Honestly it's too raw for me. I found an alternative meanwhile, controlloid, which fit my needs.

**Comment by medape** [comment]
@rmst: Could you close this issue and #17? They're not needed anymore (and arbitrary controllers is being discussed on #33 anyways).
