### ISSUE TITLE
Support multiple devices

### ISSUE THREAD

**Issue by benkuly** [rmst/yoke#20]
Great app, but would be perfect, when it supports more then one devices to play with friends.

**Comment by rmst** [comment]
You should be able to have multiple devices by specifying a custom port and name, e.g.

```yoke --port PORT --name device2```

and then connect according to the instructions

**Comment by benkuly** [comment]
It seems to be hardcoded for only one device on Windows (vJoy).
service.py line 100
`self.device = VjoyDevice(1)  `

**Comment by rmst** [comment]
Ah right, on Windows. Could you verify if it works if you manually change that to `2` after starting the first yoke instance and before starting the second? Then, I'd add an extra command line option for that.

**Comment by benkuly** [comment]
Yes, that works 👍

**Comment by rmst** [comment]
Great, thanks! Fixed in master and added to readme. Please reopen if it doesn't work!

**Comment by pzmarzly** [comment]
For future reference, commit is https://github.com/rmst/yoke/commit/8960266e83b60f78a768e3af783302e36220dc86
