### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by plantroon** [rmst/yoke#44]
If I understand it correctly, the desktop app is basically a vjoy feeder.

Upon installing and running it, I get an error like this:
```
PS C:\Python38\Scripts> python .\yoke
Warning: This is not well tested on Windows!
Checking files on webserver… OK.
Writing manifest… OK.
Starting webserver on  64780 C:\Python38\lib\site-packages\yoke\assets\joypad

To connect select "rift-Yoke-1" on your device,
or connect manually to "10.91.1.112:64780"
Press Ctrl+C to exit.
Connected to  ('10.91.1.181', 37319)
Shutting down…
Traceback (most recent call last):
  File ".\yoke", line 17, in <module>
    service.run()
  File "C:\Python38\lib\site-packages\yoke\service.py", line 350, in run
    v = self.preprocess(m, len(self.dev.events))
  File "C:\Python38\lib\site-packages\yoke\service.py", line 281, in preprocess
    v = tuple([int(m) for m in v])
  File "C:\Python38\lib\site-packages\yoke\service.py", line 281, in <listcomp>
    v = tuple([int(m) for m in v])
ValueError: invalid literal for int() with base 10: b' -0.17202751 0.835325 9.769495 0.0 0.0 0.0 0.0'
```
I can help with the testing but my Python (or any programming) knowledge is limited.

**Comment by medape** [comment]
I'm sorry I just saw this now. This project tends to go inactive for long periods of time, I didn't contribute lately either, and I'm not currently following anything so I forgot about this email account.

You're right: the desktop app is a vJoy feeder, or a uinput feeder if you're using Linux. It's supposed to be cross-platform.

It looks to me like you're mixing versions somehow. Your desktop app expects integers, but your APK is a bit outdated and it's sending floats. You should be able to download the most up-to-date version at https://github.com/rmst/yoke/blob/master/devel/app-debug.apk or compile it yourself if you want the Brazilian Portuguese version at rmst/yoke-android@98738f53f51a0ea11b4a5e891342b5f347ab9f8a

There's also an updated manual that wasn't merged to this repo yet; check medape/yoke. The README for the most up-to-date version is at https://github.com/medape/yoke/blob/master/WEBVIEW.md

**Comment by plantroon** [comment]
Thanks for the answer.

I had the version from F-droid, which was the problem. So I downloaded the .apk you suggested and it works (vjoy monitor picks up signals) but still can't get it to work in actual games. But that's a vjoy problem I guess. I'll figure it out. Thanks for the help.
