### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by zezinho42** [rmst/yoke#45]
I followed all the readme, and got stuck with this error, maybe I need to load a kernel module?:

python3 bin/yoke
Traceback (most recent call last):
  File "bin/yoke", line 80, in <module>
    dev = yoke.Device(args.id, args.name, events=Service.events)
  File "/home/jose/.local/lib/python3.8/site-packages/yoke/service.py", line 73, in __init__
    self.device = uinput.Device(events, name, BUS_VIRTUAL)
  File "/home/jose/.local/lib/python3.8/site-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/home/jose/.local/lib/python3.8/site-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/home/jose/.local/lib/python3.8/site-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
OSError: [Errno 19] Failed to open the uinput device: No such device

**Comment by pzmarzly** [comment]
> I need to load a kernel module

You are on the right track. Could you try running `sudo modprobe uinput`?

Have you run [`yoke-enable-uinput`](https://github.com/rmst/yoke/blob/7cf90f413fae5ab3f97e67697bef77f3f8a28ec2/bin/yoke-enable-uinput)? I'm not sure if it even does anything with module loading, but it may be needed too.

**Comment by zezinho42** [comment]
> > I need to load a kernel module
> 
> You are on the right track. Could you try running `sudo modprobe uinput`?

That was it. Maybe it could be added to the README? Or even better, hint given by yoke when on input is found?

**Comment by pzmarzly** [comment]
> Or even better, hint given by yoke when on input is found?

That's a good idea, thanks. I implemented a basic version of it in #46 . There is a room for improvement (e.g. colored terminal output), but right now `yoke` is rather stale and I'd prefer not to make any big changes to it (if anyone reading this wants to take over Yoke's development, though, go ahead - there is a lot that can be done for this project).
