### ISSUE TITLE
"Nothing" on Slackware

### ISSUE THREAD

**Issue by bad-interpreter** [rmst/yoke#5]
I just installed the client on a Slackware64 -current machine. Pip3 installed everything flawlessly, but I had to manually add the udev rule (there's no addgroup command in slackware, we use groupadd, and personally I prefer not to use sudo). I can start the server correctly: it stands echoing
```
Starting service... Press Ctrl+C to exit.
To connect, select "zion.inet-Yoke" on your device.
```

but the app on my phone keeps saying "connect to **nothing**".

**Comment by rmst** [comment]
When you click on "connect to nothing" it doesn't show you your computer? Have you checked that both devices are on the same private network?

**Comment by bad-interpreter** [comment]
If I click on it doesn't show anything else. And yes, they are in the same logical net!

**Comment by rmst** [comment]
Perhaps the network doesn't support zeroconf which we use to find the server. One workaround could be to connect to the laptop directly via bluetooth/wifi/usb thether (and for debugging disable any other networks (except mobile data) on both devices). That's obviously not perfect but could help us pin down the problem.

**Comment by bad-interpreter** [comment]
Well, knowing that the targeting is based on zeroconf is definitely something to say! I'm on a structured network, with a hybrid static / dhcp setup and a local dns server, so zeroconf is not part of the game!
Just for testing purposes, I enabled avahi daemons in order to use zeroconf, but nothing changed.
A Bluetooth connection is not an option as I haven't any BT capability on my pc.
I tried the USB-Tethering connection, but as you can see, we still get "nothing".

![screenshot_yoke_20180915-103259](https://user-images.githubusercontent.com/35395283/45584421-606a7580-b8d3-11e8-96b9-37c1103207f4.png)

Is there the possibility to target the server manually?

**Comment by rmst** [comment]
USB/Wifi/Bluetooth tethering should work as long as you disable all other
networks (except mobile) on both devices. I can see that you are still
connected to wifi on your phone which might prevent zeroconf from looking
at the network created for USB tethering.

It's currently not possible to enter an ip address manually but we should
probably add that.

**Comment by bad-interpreter** [comment]
Well, this makes actually any difference!

![screenshot_yoke_20180916-161006](https://user-images.githubusercontent.com/35395283/45597362-6c396300-b9cb-11e8-8fff-171eb3f8258a.png)
This is my phone pinging my pc (the client on which yoke is listening) in which I disabled all the network connections but the USB tethering.

Still getting nothing!

**Comment by rmst** [comment]
Hm, very strange. Anyway, I just released another version that allows for manual connections. It should become available on Goolge Play in a couple of minutes and also on F-Droid but I don't know how long it will take there. Please reopen this issue if you still can't connect after installing the new version!

**Comment by bad-interpreter** [comment]
Well, just upgraded yoke and it doesn't seem to like any "--port" argument
```
# yoke --port 1248
usage: yoke [-h] [--name NAME] [--type {gamepad,flightgear}]
yoke: error: unrecognized arguments: --port 1248
```

**Comment by rmst** [comment]
Ah, I forgot to push it. Now it should work.

**Comment by rmst** [comment]
Great! Thanks for trying it out!
