### ISSUE TITLE
executing yoke on Linux: OSError: [Errno 19] 

### ISSUE THREAD

**Issue by KHZ-INTL** [rmst/yoke#9]
Hi,
I am running on Arch Linux, kernel 4.18.10.

When executing yoke on Linux I get error number 19. I have followed all the steps on the Github readme. I added a new group and added my self to it per yoke-enable-uinput script. Any help is appreciated. The error:

Traceback (most recent call last):
  File "/usr/bin/yoke", line 41, in <module>
    dev = yoke.Device(args.name, events=Service.events)
  File "/usr/lib/python3.7/site-packages/yoke/service.py", line 67, in __init__
    self.device = uinput.Device(events, name, BUS_VIRTUAL)
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 178, in __init__
    self.__uinput_fd = fd or fdopen()
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 84, in fdopen
    return _libsuinput.suinput_open()
  File "/usr/lib/python3.7/site-packages/uinput/__init__.py", line 70, in _open_error_handler
    raise OSError(code, msg)
OSError: [Errno 19] Failed to open the uinput device: No such device

**Comment by wonbinbk** [comment]
Hi, 
I have the same issue.
Did you manage to solve it? If so, please share your solution.

**Comment by KHZ-INTL** [comment]
Hi,
I resolved the issue. I did so many things that I am unsure which one of the was the actual solution. However, I am happy to suggest them to you.
@wonbinbk 
+ Are you running Arch Linux ?, 
+ Do you have the dependencies installed ?,
+ Did you restart your PC?

**Comment by wonbinbk** [comment]
Hi,
Thank you for replying.
I resolved the issue with the help of the author.
All I need to do was to probe the driver for "uinput".

I'm using Arch Linux (well, Manjaro, but hey it's still Arch :)) and I'm loving it!

**Comment by KHZ-INTL** [comment]
Hi,
Please provide the details for the fix, it will be great for others seeking help. 
Indeed, happy with my arch setup, running Xmonad.

Sincerely,
KHZ

**Comment by wonbinbk** [comment]
Check in the driver is probed with

'lsmod | grep uinput'

Probably that will display nothing, which would mean that the driver is not loaded. Try loading it:

'sudo modprobe uinput'

After that I could run yoke with no root privilege.
